name: Feature request
description: Suggest an idea for SQL Optima Action
title: "Feature: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose an improvement!

        Before you begin, **please ensure that there are no [existing issues](https://github.com/ale94lko/sql-optima/issues)**, whether still open or closed, related to your idea.
        ---

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ale94lko/sql-optima/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem would this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you have in mind.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you thought about?
    validations:
      required: false
